import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeroClientProvider from "@/components/providers/HeroClientProvider";
import Navbar from "@/components/navbar/Navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Angel Quintero - Desarrollador Web",
  description: "Generated by create next app",
  icons: {
    icon: "/aq.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="dark text-foreground bg-background">
      <body className={`${inter.variable} font-sans antialiased`}>
        <HeroClientProvider>
          <Navbar />
          {children}
        </HeroClientProvider>
      </body>
    </html>
  );
}
